export const FETCH_TODOS_LIST = "FETCH_TODOS_LIST";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";

export const FAILED_REQUEST = "FAILED_REQUEST";

export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
